### ISSUE TITLE
Question about Robust04

### ISSUE THREAD

**Issue by CSQianDong** [Georgetown-IR-Lab/cedr#15]
Hi, I am intersted to your work. Could you release the codes about how to preprocess the raw TREC Robust04 dataset? I want to reproduce the results in your paper. However I failed, I think the problem must in the step of data-preprocessing. Appreciate for your help~

**Comment by seanmacavaney** [comment]
Hi @DQ0408,

Unfortunately the collection license agreement prevents us from distributing it. However, I'm currently in the process of putting together code that should make it easier to reproduce the results. I'll keep you posted.

 - sean

**Comment by CSQianDong** [comment]
Hi, thank you for your reply. I already have the data of collection. Is it possible to release the data-preprocessing codes only? If not, could you give me some hints about this step? Really appreciate for your help~

**Comment by seanmacavaney** [comment]
Yup-- it will include code for all the pre-processing/indexing/etc.

**Comment by CSQianDong** [comment]
Looking forward to your next works!
