### ISSUE TITLE
Indri index

### ISSUE THREAD

**Issue by xuezzz** [Georgetown-IR-Lab/cedr#17]
I couldn't find out how to build indri index. Could you tell me more about this? Thank you!

**Comment by seanmacavaney** [comment]
Indri can be built using the `IndriBuildIndex` command. More information about Indri building can be found here: https://sourceforge.net/p/lemur/wiki/IndriBuildIndex%20Parameters/

**Comment by xuezzz** [comment]
> Indri can be built using the `IndriBuildIndex` command. More information about Indri building can be found here: https://sourceforge.net/p/lemur/wiki/IndriBuildIndex%20Parameters/

OK, I got it, thanks for your help!
