### ISSUE TITLE
Release Bert Baseline model

### ISSUE THREAD

**Issue by Albert-Ma** [Georgetown-IR-Lab/cedr#18]
I want to ask if it's convenient to release the bert baseline model ckpt?
Thanks~

**Comment by seanmacavaney** [comment]
Hey @Albert-Ma -- see the following for checkpoints of the BERT and CEDR-KNRM models on each of the 5 folds of Robust: https://macavaney.us/cedr-models.tar (to be moved to a more permanent location later). Hope this helps!

**Comment by CSQianDong** [comment]
Hello, could you release ckpt file of WebTrack? Thanks a lot~

**Comment by CSQianDong** [comment]
And manifest.json to preprocess clueweb data. Really thanks..
