### ISSUE TITLE
consider using pytrec_eval

### ISSUE THREAD

**Issue by cmacdonald** [Georgetown-IR-Lab/cedr#2]
Would you consider using [pytrec_eval](https://github.com/cvangysel/pytrec_eval) for validation purposes, instead of trec_eval?

I think there are several advantages of doing so:

1. You don't have to ship/rely on trec_eval, which might not be complied for the correct platform. In contrast, I think that relying on pytrec_eval means that its compiled as appropriate.

2. This means that if we provide a "dataset" that contains labels as input, we dont need to have a separate qrels file.

3. You don't need to fork a separate process to run trec_eval, so it should be faster.

**Comment by seanmacavaney** [comment]
Hi Craig,

Thanks-- these are all good points. I was initially using pytrec_eval, but switched because I needed custom metric parameters ([which are not yet supported](https://github.com/cvangysel/pytrec_eval/issues/12)) for some of my experiments.

**Comment by cmacdonald** [comment]
ah interesting motivation. You might want to have an evaluator base class, that can be instantiated for both scenarios.

**Comment by seanmacavaney** [comment]
Done with #25
