### ISSUE TITLE
Could you release manifest.json? Thanks a lot~

### ISSUE THREAD

**Issue by CSQianDong** [Georgetown-IR-Lab/cedr#30]

**Comment by seanmacavaney** [comment]
Can you please clarify?

**Comment by CSQianDong** [comment]
This file is used to build index. use code: IndriBuildIndex manifest.json

**Comment by seanmacavaney** [comment]
Here's the manifest for the Robust collection. Nothing fancy: https://macavaney.us/misc/robust-manifest.xml

The file I have is a manifest.xml file -- not manifest.json. Have newer versions of indri moved to json for configuration? I'm not sure.

**Comment by CSQianDong** [comment]
Thanks!
