### ISSUE TITLE
How were the train pairs for Robust made?

### ISSUE THREAD

**Issue by nirmal2k** [Georgetown-IR-Lab/cedr#42]
I couldn't find some training pairs in qrels.
Also is eval data for robust used as training data?

**Comment by seanmacavaney** [comment]
Training pairs and qrels are found here: https://github.com/Georgetown-IR-Lab/cedr/tree/master/data

We used the standard Robust04 5-folds from Huston & Croft (2014).

I recommend using [OpenNIR](https://github.com/Georgetown-IR-Lab/OpenNIR) instead of this repository.

**Comment by nirmal2k** [comment]
Can you please confirm that the training is done on eval qrels?
Thanks

**Comment by seanmacavaney** [comment]
We used 5-fold cross validation over Robust04. So in other words, 5 models were trained, each using 3 folds for training, one for tuning (e.g., tuning the training epoch), and the final one held out for evaluation.
